name: hivedb_example
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  provider: ^4.1.3
  http: ^0.12.1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.10

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0
  hive_generator: ^0.7.0+2

dependency_overrides:
  hive:
    git:
      url: https://github.com/hivedb/hive
      path: hive
  hive_generator:
    git:
      url: https://github.com/hivedb/hive
      path: hive_generator
  hive_flutter:
    git:
      url: https://github.com/hivedb/hive
      path: hive_flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/Dancing_Script/DancingScript-Regular.ttf
        - asset: assets/fonts/Dancing_Script/DancingScript-Bold.ttf
          weight: 700
        - asset: assets/fonts/Dancing_Script/DancingScript-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Dancing_Script/DancingScript-Medium.ttf
          weight: 500
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf
